name: "[functions:node] Deploy to Staging"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
    paths:
      - "apps/functions/**"
      - "package.json"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout from ${{ github.head_ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.9.0
      - name: Functions - Set firebase env to Develop
        uses: w9jds/firebase-action@v13.15.2
        with:
          args: functions:config:set runtime.env="develop" algolia.appid="${{ secrets.ALGOLIA_APPID_DEV }}" algolia.apikey="${{ secrets.ALGOLIA_APIKEY_DEV }}" algolia.apikeyadmin="${{ secrets.ALGOLIA_APIKEYADMIN_DEV }}" --project default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Functions - Build for develop
        run: pnpm install && cd apps/functions && pnpm build
      - name: Functions - Deploy to develop
        uses: w9jds/firebase-action@v13.15.2
        with:
          args: deploy --only functions,firestore:rules --project default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
