# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master, develop ]
  schedule:
    - cron:  '0 5,17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Hosting - Install dependencies
      run: cd hosting && yarn install
    - name: Hosting - Test
      run: cd hosting && yarn test
    - name: Hosting - Generate html files for production
      run: yarn run build
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_PRD }}
        ALGOLIA_CONFIG: ${{ secrets.ALGOLIA_CONFIG_PRD }}
        GA_ADSENSE_ID: ${{ secrets.GA_ADSENSE_ID }}
      if: ${{ github.ref == 'refs/heads/master' }}
    - name: Hosting - Generate html files for develop
      run: yarn run build
      env:
        NODE_ENV: development
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_DEV }}
        ALGOLIA_CONFIG: ${{ secrets.ALGOLIA_CONFIG_DEV }}
        GA_ADSENSE_ID: ${{ secrets.GA_ADSENSE_ID }}
      if: ${{ github.ref != 'refs/heads/master' }}
    - name: Functions - Set env to Production
      uses: w9jds/firebase-action@master
      with:
        args: functions:config:set runtime.env="production" algolia.appid="${{ secrets.ALGOLIA_APPID_PRD }}" algolia.apikey="${{ secrets.ALGOLIA_APIKEY_PRD }}" algolia.apikeyadmin="${{ secrets.ALGOLIA_APIKEYADMIN_PRD }}" auth.user="${{ secrets.BAUTH_USER }}" auth.password="${{ secrets.BAUTH_PASSWORD }}" --project production
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Functions - Init for production
      run: cd functions && yarn install && yarn build
      env:
        BAUTH_USER: ${{ secrets.BAUTH_USER }}
        BAUTH_PASSWORD: ${{ secrets.BAUTH_PASSWORD }}
      if: ${{ github.ref == 'refs/heads/master' }}
    - name: Deploy to Production
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting,functions --project production
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Set env to Develop
      uses: w9jds/firebase-action@master
      with:
        args: functions:config:set runtime.env="develop" algolia.appid="${{ secrets.ALGOLIA_APPID_DEV }}" algolia.apikey="${{ secrets.ALGOLIA_APIKEY_DEV }}" algolia.apikeyadmin="${{ secrets.ALGOLIA_APIKEYADMIN_DEV }}" auth.user="${{ secrets.BAUTH_USER }}" auth.password="${{ secrets.BAUTH_PASSWORD }}" --project default
      if: ${{ github.ref != 'refs/heads/master' }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Init functions for develop
      run: cd functions && yarn install && yarn build
      env:
        BAUTH_USER: ${{ secrets.BAUTH_USER }}
        BAUTH_PASSWORD: ${{ secrets.BAUTH_PASSWORD }}
      if: ${{ github.ref != 'refs/heads/master' }}
    - name: Deploy to Develop
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting,functions --project default
      if: ${{ github.ref != 'refs/heads/master' }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
