name: "[functions:node] Deploy to Staging"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
    paths:
      - "apps/functions/**"
      - "packages/schemas/**"
      - "packages/utils/**"
      - "firebase.json"
      - "package.json"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout from ${{ github.head_ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.9.0
      - name: Functions - Set firebase env to Develop
        uses: w9jds/firebase-action@v13.15.2
        with:
          args: functions:config:set runtime.env="develop" algolia.appid="${{ secrets.ALGOLIA_APPID_DEV }}" algolia.apikey="${{ secrets.ALGOLIA_APIKEY_DEV }}" algolia.apikeyadmin="${{ secrets.ALGOLIA_APIKEYADMIN_DEV }}" --project default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Enable Artifact Registry API (ensure migration prereq)
        uses: w9jds/firebase-action@v13.15.2
        with:
          args: --version  # This step ensures the Firebase action environment is ready
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        continue-on-error: true
      - name: Install dependencies
        run: pnpm install
      - name: Schemas - Build for develop
        working-directory: packages/schemas
        run: |
          pnpm build
          echo "Schemas build output:"
          ls -la dist/ | head -10
      - name: Utils - Build for develop
        working-directory: packages/utils
        run: |
          pnpm build
          echo "Utils build output:"
          ls -la dist/ | head -10
      - name: Functions - Build for develop
        working-directory: apps/functions
        run: |
          rm -rf dist
          pnpm build
          node scripts/inline-local-packages.js
      - name: Verify build output
        run: ls -la apps/functions/dist/ | head -20
      # TODO: FIREBASE_TOKEN is deprecated. Consider migrating to Service Account authentication:
      # https://cloud.google.com/docs/authentication/getting-started
      - name: Functions - Delete existing v1 functions (required for v1→v2 migration)
        uses: w9jds/firebase-action@v13.15.2
        with:
          args: functions:delete api onPostCreate onPostUpdate onActivityCreate onSecretCreate --project default --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        continue-on-error: true
      - name: Functions - Deploy v2 functions to develop (attempt 1)
        id: deploy_attempt_1
        uses: w9jds/firebase-action@v13.15.2
        with:
          args: deploy --only functions,firestore:rules --project default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        continue-on-error: true
      - name: Wait for Eventarc Service Agent setup (30 secounds)
        if: steps.deploy_attempt_1.outcome == 'failure'
        run: |
          echo "First deployment failed, likely due to Eventarc Service Agent setup. Waiting 30 seconds..."
          sleep 30
      - name: Functions - Deploy v2 functions to develop (attempt 2)
        if: steps.deploy_attempt_1.outcome == 'failure'
        uses: w9jds/firebase-action@v13.15.2
        with:
          args: deploy --only functions,firestore:rules --project default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
