# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Hosting CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: yarn test
    - name: Init functions
      run: cd functions && npm install && npm run build
    - name: Generate html files
      run: yarn run build
      env:
        FIREBASE_CONFIG_PRD: ${{ secrets.FIREBASE_CONFIG_PRD }}
        FIREBASE_CONFIG_DEV: ${{ secrets.FIREBASE_CONFIG_DEV }}
        GA_ADSENSE_ID: ${{ secrets.GA_ADSENSE_ID }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting,functions --
        hosting:
          - production
            if: ${{ github.ref == 'master' }}
          - staging
            if: ${{ github.ref == 'develop' }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

