name: UnitTest

on: pull_request

jobs:
  unittest:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Setup Yarn
      run: npm install yarn -g

    - name: Install Dependencies
      run: cd www && yarn install
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_PRD }}
        ALGOLIA_CONFIG: ${{ secrets.ALGOLIA_CONFIG_PRD }}
        GA_ADSENSE_ID: ${{ secrets.GA_ADSENSE_ID }}
        FCM_VAPID_KEY: ${{ secrets.FCM_VAPID_KEY_PRD }}
      
    - name: Unit Test with Coverage
      run: yarn test:coverage
